name: 'crypro-currencies'
pool:
  vmImage: ubuntu-latest

variables:
  - group: crypto-settings
  - name: buildConfiguration
    value: 'Release'
  - name: dotNetFramework
    value: 'net6.0'
  - name: major
    value: 1
  - name: minor
    value: 0
  - name: patch
    value: $[counter(variables['minor'], 0)]
  - name: version
    value: $(major).$(minor).$(patch)


steps:

  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 6.0.301
      includePreviewVersions: true
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: "msbuild test"
    inputs:
      command: custom
      custom: 'msbuild'
      arguments: 'CryptoCurrencies.Test.csproj /p:Configuration=Release /t:VSTest'
      workingDirectory: 'test/'

  - task: DotNetCoreCLI@2
    displayName: "msbuild pack"
    inputs:
      command: custom
      custom: 'msbuild'
      arguments: 'CryptoCurrencies.csproj /p:Version=$(version) /p:BuildPackage=true /p:Configuration=Release /t:Restore /t:build /t:pack'
      workingDirectory: 'src/'

  - task: NuGetAuthenticate@0
    displayName: 'Authenticate in NuGet feed'
  - script: dotnet nuget push bin/**/*.nupkg  --source https://api.nuget.org/v3/index.json --api-key $(nuget-api-key)
    displayName: 'Uploads nuGet packages'
    workingDirectory: 'src/'

  - task: PostBuildCleanup@3
